version: "3.8"

services:
  frontend:
    build: ./blip-react
    container_name: blip-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build: ./api
    container_name: blip-backend
    restart: unless-stopped
