services:
  frontend:
    image: ghcr.io/julie12yu/blip:latest
    container_name: blip-frontend
    command: npx serve -s /app/frontend/build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    image: ghcr.io/julie12yu/blip:latest
    container_name: blip-backend
    command: python /app/backend/main.py
    restart: unless-stopped
